FROM nvidia/cuda:10.2-cudnn8-runtime-ubuntu20.04
RUN apt-get update -yy
RUN apt-get install -yy --no-install-recommends \
    git curl wget build-essential libhdf5-dev \
    libgl1-mesa-glx libglib2.0-0 software-properties-common

ENV PYTHON_VERSION 3.8
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-cache policy python$${PYTHON_VERSION}
RUN apt-get install -yy --no-install-recommends \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-pip \
    python${PYTHON_VERSION}-dev

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir  torch==1.12.1

