FROM nvidia/cuda:11.3.0-runtime-ubuntu18.04
RUN apt-get update -yy
RUN apt-get install -yy --no-install-recommends \
  git curl wget build-essential libhdf5-dev \
  libgl1-mesa-glx libglib2.0-0 software-properties-common

ENV PYTHON_VERSION 3.8
RUN add-apt-repository ppa:deadsnakes/ppa \
&& apt-get update -yy \
&& apt-get install -yy --no-install-recommends python3.8 python3.8-distutils python3.8-dev \
&& rm -f /usr/bin/python3 /usr/bin/python \
&& ln -s /usr/bin/python3.8 /usr/bin/python3 \
&& ln -s /usr/bin/python3.8 /usr/bin/python \
&& wget -q https://bootstrap.pypa.io/get-pip.py \
&& python get-pip.py

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir  torch==1.12.1

